[ 2024-10-22 09:55:32,513 ] 7 src.logger.custom_logging - INFO - >>>>>> stage Data Ingestion stage started <<<<<<
[ 2024-10-22 09:55:32,513 ] 12 src.logger.custom_logging - ERROR - [Errno 2] No such file or directory: 'config/config.yaml'
Traceback (most recent call last):
  File "/Users/akashmukherjee/Programming/MLOPS/Bappy/Wine quality/main.py", line 9, in <module>
    data_ingestion.main()
  File "/Users/akashmukherjee/Programming/MLOPS/Bappy/Wine quality/src/pipeline/data_ingestion_pipe.py", line 17, in main
    config = ConfigManager()
             ^^^^^^^^^^^^^^^
  File "/Users/akashmukherjee/Programming/MLOPS/Bappy/Wine quality/src/config/configuration.py", line 11, in __init__
    self.config=read_yaml(config_filepath)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akashmukherjee/Programming/MLOPS/Bappy/Wine quality/my_env/lib/python3.11/site-packages/ensure/main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akashmukherjee/Programming/MLOPS/Bappy/Wine quality/src/utils/utlis.py", line 26, in read_yaml
    raise e
  File "/Users/akashmukherjee/Programming/MLOPS/Bappy/Wine quality/src/utils/utlis.py", line 18, in read_yaml
    with open (path_to_yaml)as f:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.yaml'
[ 2024-10-22 09:55:59,720 ] 7 src.logger.custom_logging - INFO - >>>>>> stage Data Ingestion stage started <<<<<<
[ 2024-10-22 09:55:59,720 ] 12 src.logger.custom_logging - ERROR - [Errno 2] No such file or directory: 'config/config.yaml'
Traceback (most recent call last):
  File "/Users/akashmukherjee/Programming/MLOPS/Bappy/Wine quality/main.py", line 9, in <module>
    data_ingestion.main()
  File "/Users/akashmukherjee/Programming/MLOPS/Bappy/Wine quality/src/pipeline/data_ingestion_pipe.py", line 17, in main
    config = ConfigManager()
             ^^^^^^^^^^^^^^^
  File "/Users/akashmukherjee/Programming/MLOPS/Bappy/Wine quality/src/config/configuration.py", line 11, in __init__
    self.config=read_yaml(config_filepath)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akashmukherjee/Programming/MLOPS/Bappy/Wine quality/my_env/lib/python3.11/site-packages/ensure/main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akashmukherjee/Programming/MLOPS/Bappy/Wine quality/src/utils/utlis.py", line 26, in read_yaml
    raise e
  File "/Users/akashmukherjee/Programming/MLOPS/Bappy/Wine quality/src/utils/utlis.py", line 18, in read_yaml
    with open (path_to_yaml)as f:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.yaml'
